name: Basic CI/CD Pipeline
on: push
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Clone Repository
			  uses: actions/checkout@v3
			- name: Python Environment
			  uses: actions/python@v3
			  with:
			    python-version: "3.10"
			- name: Dependencies Installation
			  run: pip3 install -r requirements.txt
			- name: TestCases Execution
			  run: pytest test.py
